geprek_lensu/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import include, path
from main.views import create_product_flutter, show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml 
from main.views import show_main, create_product, show_xml, show_json
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import add_stock
from main.views import reduce_stock
from main.views import add_stock
from main.views import delete_product
from main.views import edit_product
from main.views import delete_product
from main.views import get_product_json
from main.views import create_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_stock/<int:id>/', add_stock, name='add_stock'),
    path('reduce-stock/<int:id>/', reduce_stock, name='reduce_stock'),
    path('delete-product/<int:id>/', delete_product, name='delete_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    # path('delete/<int:id>', delete_product, name='delete_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', create_ajax, name='create_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    menu = models.CharField(max_length=255)
    price = models.IntegerField(default=0)
    stock = models.IntegerField(default=0)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def add_stock(self, quantity):
        self.stock += quantity
        self.save()
        return f"Berhasil menambahkan stock sebanyak {quantity}. Jumlah stock {self.menu} saat ini adalah {self.stock}."

    def order(self):
        self.stock -= 1
        self.save()
        return f"Pelanggan berhasil memesan 1 porsi {self.menu}! Jumlah stock {self.menu} saat ini adalah {self.stock}."

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["menu", "price", "stock", "description"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product # nambahin sendiri
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound, HttpResponseRedirect
import json

@login_required(login_url='/login')
# Create your views here.
def show_main(request):
    products = Product.objects.filter(user=request.user)
    item_count = products.count()

    context = {
        'app' : 'Geprek Lensu',
        'name': request.user.username,
        'class': 'PBP F',
        'products' : products,
        'item_count': item_count,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        print("Heeeellloooo")
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            print("Halo")
            return response
        else:
            print("Hi")
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_stock(request, id):
    try:
        product = Product.objects.get(pk=id)
        if product.stock > 0:
            product.stock += 1
            product.save()
    except Product.DoesNotExist:
        pass

    return redirect('main:show_main')

def reduce_stock(request, id):
    try:
        product = Product.objects.get(pk=id)
        if product.stock > 0:
            product.stock -= 1
            product.save()
    except Product.DoesNotExist:
        pass
    
    return redirect('main:show_main')

def delete_product(request, id):
    product = get_object_or_404(Product, pk=id)
    product.delete()

    return redirect('main:show_main')

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def create_ajax(request):
    if request.method == 'POST':
        menu = request.POST.get("menu")
        price = request.POST.get("price")
        stock = request.POST.get("stock")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(menu=menu, price=price, stock=stock, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            menu = data["menu"],
            stock = int(data["stock"]),
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: #E03930;
    }
</style>
<div class="container">
    <h1 class="mt-5 mb-4" style="color: white;">Tambahkan Menu Untuk Restoran Geprek Lensu</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="menu" class="form-label" style="color: white;">Nama Menu:</label>
            <input type="text" name="menu" id="menu" class="form-control" placeholder="Masukkan Nama Menu" required>
        </div>
        <div class="mb-3">
            <label for="price" class="form-label" style="color: white;">Harga:</label>
            <input type="number" name="price" id="price" class="form-control" placeholder="Masukkan Harga" required>
        </div>
        <div class="mb-3">
            <label for="stock" class="form-label" style="color: white;">Jumlah Stok:</label>
            <input type="number" name="stock" id="stock" class="form-control" placeholder="Masukkan Stock" required>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label" style="color: white;">Deskripsi:</label>
            <textarea name="description" id="description" class="form-control" rows="4" placeholder="Masukkan Deskripsi" required></textarea>
        </div>
        <div class="d-grid">
            <button class="btn" type="submit" style="background-color: #EAD9A3; color:#E03930; font-weight: 600;">Update Product</button>
        </div>
    </form>
</div>
{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #EAD9A3;
    }
</style>

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card" style="background-color: #E03930; color: white;">
        <div class="card-body">
            <h1 class="card-title text-center">Login</h1>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" name="username" id="username" class="form-control" placeholder="Username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
                </div>
                <div class="d-grid">
                    <button class="btn" type="submit" style="background-color: #EAD9A3; color:#E03930; font-weight: 600;">Login</button>
                </div>                
            </form>

            {% if messages %}
                <ul class="mt-3">
                    {% for message in messages %}
                        <li class="text-danger">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <p class="mt-3 text-center">Don't have an account yet? <a href="{% url 'main:register' %}" style="color: white;">Register Now</a></p>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <body>
        <div class="navbar">
            <div class="left-section">
                <a href="#" class="logo" style="color: #E03930;">Geprek Lensu</a>
                <a href="{% url 'main:create_product' %}" class="add-item-button">Tambah Item</a>
            </div>
            <div class="right-section">
                <a href="{% url 'main:logout' %}" class="logout-button" style="font-weight: 600;">Logout</a>
            </div>
        </div>
    </body>

    <div class="body">
        <div class="hero-container">
            <div class="hero">
                <div class="hero-text" style="text-align: center;">
                    <h1 style="font-weight: bold;">Nikmati Pedasnya Hidup di Geprek Lensu!</h1>
                </div>
            </div>            
            <div class="title-card">
                <div class="text-card">
                    <div class="text">
                           <h1 style="padding-bottom: 5px; color: #EAD9A3;">Hai, {{ name }}!</h1>
                        {% with item_count=products|length %}
                            <h5 class="icon-keranjang">
                                <i class="fas fa-shopping-cart"></i>
                                <span style="margin-left: 10px;">{{ item_count }} item</span>
                            </h5>
                            <h5 class="icon-jam">
                                <i class="far fa-clock fa-lg"></i>
                                <span style="margin-left: 10px;">Last Login: {{ last_login }}</span>
                            </h5>
                            <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#addProductModal" style="width: 800; display: block; margin: 0 auto; background-color: #EAD9A3; color: #E03930; font-weight: 600;">Add Product by AJAX</button>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>

        
        <div class="modal fade" id="addProductModal" tabindex="-1" aria-labelledby="addProductModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content" style="background-color: #EAD9A3;">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="addProductModalLabel" style="color: #E03930; font-weight: 600;">Add New Product</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="menu" class="form-label" style="color: #866237; font-weight: 600;">Nama Menu:</label>
                                <input type="text" name="menu" id="menu" class="form-control" placeholder="Masukkan Nama Menu" required>
                            </div>
                            <div class="mb-3">
                                <label for="price" class="form-label" style="color: #866237; font-weight: 600;">Harga:</label>
                                <input type="number" name="price" id="price" class="form-control" placeholder="Masukkan Harga" required>
                            </div>
                            <div class="mb-3">
                                <label for="stock" class="form-label" style="color: #866237; font-weight: 600;">Jumlah Stok:</label>
                                <input type="number" name="stock" id="stock" class="form-control" placeholder="Masukkan Stock" required>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="form-label" style="color: #866237; font-weight: 600;">Deskripsi:</label>
                                <textarea name="description" id="description" class="form-control" rows="4" placeholder="Masukkan Deskripsi" required></textarea>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn" data-bs-dismiss="modal" style="background-color: #EAD9A3; color:#E03930; border-color: #E03930; font-weight: 600;">Close</button>
                        <button type="button" class="btn" id="button_add" data-bs-dismiss="modal" style="background-color: #E03930; color:#EAD9A3; font-weight: 600;">Add Product</button>
                    </div>                    
                </div>
            </div>
        </div>

        <table id="product_table">
            <tr>
                <th style="display: none;">Name</th>
                <th style="display: none;">Price</th>
                <th style="display: none;">Stock</th>
                <th style="display: none;">Description</th>
            </tr>
        </table>
        
        
        <div class="row" id="product_cards">
            
            
        </div>
        

        <br />

    </div>

    <script>
         async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            const items = await getProducts();
            document.getElementById("product_cards").innerHTML = "";
            let htmlString = ""
            console.log(items)
            items.forEach((product) => {
            htmlString += `\n
            <div class="card-body">
                    <div class="card-element" style="color: #866237;">
                        <h5 class="card-title" style="font-weight: 700; margin-bottom: 10px;">${product.fields.menu}</h5>
                        <p class="card-text" style="font-weight: 600; margin-bottom: 10px;">
                            <i class="fas fa-info-circle"></i> <span class="icon-text"></span> ${product.fields.description}
                        </p>
                        <div class="info-group">
                            <div class="info" style="margin-bottom: 10px;">
                                <i class="fas fa-dollar-sign"></i>
                                <span class="icon-text"></span> ${product.fields.price}
                            </div>
                            <div class="info" style="margin-bottom: 10px;">
                                <i class="fas fa-cubes"></i>
                                <span class="icon-text"></span> <span id="stock${product.pk}">${product.fields.stock}</span>
                            </div>
                        </div>                        
                        <div class="edit-delete">
                            <a href="edit-product/${product.pk}" class="btn btn-sm" style="background-color: #EAD9A3; color: #F8362D; border-radius: 10px; border: none; margin-top: 10px;">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="delete-product/${product.pk}" class="btn btn-sm" style="background-color: #EAD9A3; color: #F8362D; border-radius: 10px; border: none; margin-top: 10px;">
                                <i class="fas fa-trash"></i>
                            </a>
                            <a href="add_stock/${product.pk}" class="btn btn-sm" style="background-color: #EAD9A3; color: #F8362D; border-radius: 10px; border: none; margin-top: 10px;"">
                                <i class="fas fa-plus"></i>
                            </a>
                            <a href="reduce-stock/${product.pk}" class="btn btn-sm" style="background-color: #EAD9A3; color: #F8362D; border-radius: 10px; border: none; margin-top: 10px;"">
                                <i class="fas fa-minus"></i>
                            </a>
                        </div>
                    </div>
                </div>
            `
            })
            
            document.getElementById("product_cards").innerHTML = htmlString
        }

        refreshProducts()

        function addProduct() {
            fetch("{% url 'main:create_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            })
            .then(function (response) {
                if (response.status === 200) {
                    var myModal = new bootstrap.Modal(document.getElementById("addProductModal"));
                    myModal.hide();

                    document.getElementById("form").reset();
                }
            })
            .then(refreshProducts);

            return false;
        }

    document.getElementById("button_add").onclick = addProduct;

    </script>

    <style>
        
        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            background-color: #EAD9A3;
            color: #E03930;
            padding-left: 40px;
        }

        .logo {
            font-size: 24px;
            font-weight: bold;
            text-decoration: none
        }

        .add-item-button {
            color: #E03930;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            background-color: #EAD9A3;
            text-decoration: none
        }

        .logout-button {
            background-color: #E03930;
            color: #EAD9A3;
            border: #E03930;
            margin: 30px;
            padding: 10px;
            cursor: pointer;
            border-radius: 10px;
            text-decoration: none
        }

        .body {
            max-width: 1440px;
            padding-top: 20px;
            padding-right: 20px;
            padding-left: 20px;
            background-color: #EAD9A3;
        }

        .hero {
            background-color: #EAD9A3;
            font-family: 'ui-sans-serif', sans-serif;
            font-weight: bold;
            border-radius: 30px;
        }

        .hero-card {
            margin: 20px;
            padding-top: 10px;
            padding-bottom: 10px;
        }

        .hero-text {
            color: #E03930;
            margin: 20px;      
            font-family: 'Inter', sans-serif;
        }

        .title-card {
            background-color: #E03930;
            padding-top: 40px;
            padding-bottom: 40px;
            margin-left: 50px;
            margin-right: 50px;
            font-family: 'Inter', sans-serif;
            font-weight: bold;
            border-radius: 20px;
        }

        .text-card {
            margin: 20px;
        }

        .text {
            color: #ffffff;
            padding-left: 50px;
            margin: 20px;
            font-family: 'Inter', sans-serif;
        }

        .icon-keranjang, .icon-jam {
            display: flex;
            align-items: center;
            margin-left: 5px;
        }
        
        .row {
            flex-wrap: wrap;
            justify-content: space-between;
            padding: 30px;
        }

        .card-container {
            padding: -20px;
            flex-basis: calc(33.33% - 10px);
            margin-bottom: 10px;
        }

        .card-body {
            background-color: #cbb178;
            border: 3px solid #A68050;
            color: #E03930;
            padding: 20px;
            margin: 20px;
            border-radius: 10px;
            font-family: 'Inter', sans-serif;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .card-element {
            display: flex;
            flex-direction: column;
            text-align: center;
        }

        .card-text {
            margin: 10px;
            color: #E03930;
        }

        .icon-text {
            margin-left: 10px;
        }

        .info-group {
            display: flex;
            justify-content: center;
        }

        .btn-long {
            width: 80px;
        }


        .info {
            display: flex;
            align-items: center;
            margin-right: 20px;
        }

        .icon-text {
            margin-right: 10px;
        }

        .cookie {
            color: #ffffff;
            padding-top: 40px;
            padding-left: 50px;
            font-family: 'Inter', sans-serif;
        }
    </style>
    
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #EAD9A3;
    }
</style>

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card" style="background-color: #E03930; color: white;">
        <div class="card-body">
            <h1 class="card-title text-center">Register</h1>
            <form method="POST">
                {% csrf_token %}
                <table>
                   {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td style="text-align: center;"><input type="submit" name="submit" value="Register" /></td>
                    </tr>
                </table>
            </form>

            {% if messages %}
                <ul class="mt-3">
                    {% for message in messages %}
                        <li class="text-danger">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <p class="mt-3 text-center">Already have an account? <a href="{% url 'main:login' %}" style="color: white;">Login</a></p>
        </div>
    </div>
</div>
{% endblock content %}